# Generated by Django 5.2.11 on 2026-02-19 23:24

import os
from urllib.parse import urlparse
from django.conf import settings
from django.db import migrations
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from django.apps.registry import Apps
    from django.db.backends.base.schema import BaseDatabaseSchemaEditor


def update_site_domain(apps: "Apps", _schema_editor: "BaseDatabaseSchemaEditor") -> None:
    Site = apps.get_model("sites", "Site")
    
    base_url = os.environ.get("BASE_URL")
    # Check if we are in production using settings or env var
    is_production = getattr(settings, "DJANGO_ENVIRONMENT", "development") == "production"
    
    if base_url:
        parsed = urlparse(base_url)
        domain = parsed.netloc
        name = "Plaude Polls Backend"
    elif is_production:
        raise ValueError("BASE_URL environment variable is required in production to configure the Site domain.")
    else:
        # Fallback for dev/CI
        domain = "localhost:8000"
        name = "Plaude Polls Backend (Dev)"
    
    Site.objects.update_or_create(
        id=settings.SITE_ID,
        defaults={
            "domain": domain,
            "name": name,
        },
    )


class Migration(migrations.Migration):

    dependencies = [
        ("sites", "0002_alter_domain_unique"),
    ]

    operations = [
        migrations.RunPython(update_site_domain),
    ]
