# Generated by Django 5.2.10 on 2026-02-11 11:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('polls', '0003_poll_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='DistributionAnalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('LINK_OPEN', 'Link Open'), ('QR_SCAN', 'QR Scan'), ('EMBED_LOAD', 'Embed Load'), ('SOCIAL_SHARE', 'Social Share Click')], db_index=True, max_length=20)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('referrer', models.URLField(blank=True, max_length=500)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('poll', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='distribution_analytics', to='polls.poll')),
            ],
            options={
                'verbose_name': 'Distribution Analytics',
                'verbose_name_plural': 'Distribution Analytics',
                'ordering': ['-timestamp'],
            },
        ),
    ]
