# Generated by Django 5.2.10 on 2026-02-11 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_alter_vote_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='poll',
            name='slug',
            field=models.SlugField(blank=True, max_length=12, null=True),
        ),
    ]
