# Generated by Django 5.2.10 on 2026-02-11 17:47

import apps.core.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_populate_poll_slugs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poll',
            name='slug',
            field=apps.core.fields.RandomSlugField(blank=True, default='', help_text='Public shareable identifier', length=8, max_length=12, unique=True),
        ),
    ]
