# Generated by Django 5.2.10 on 2026-02-12 02:02

import apps.core.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0007_option_slug_question_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='vote',
            name='slug',
            field=apps.core.fields.RandomSlugField(blank=True, default='', length=8, max_length=12, null=True, unique=False),
        ),
    ]
