# Generated by Django 5.2.10 on 2026-02-12 02:08

import apps.core.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0009_populate_slugs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='option',
            name='slug',
            field=apps.core.fields.RandomSlugField(blank=True, default='', length=8, max_length=12, unique=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='slug',
            field=apps.core.fields.RandomSlugField(blank=True, default='', length=8, max_length=12, unique=True),
        ),
        migrations.AlterField(
            model_name='vote',
            name='slug',
            field=apps.core.fields.RandomSlugField(blank=True, default='', length=8, max_length=12, unique=True),
        ),
    ]
